services:
  db:
    env_file: ".env"
    image: postgres:16-alpine
    container_name: ezred2db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

volumes:
  data: