services:
  db:
    hostname: postgres
    env_file: ".env"
    image: postgres:16-alpine
    container_name: ezred2db
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
  api:
    container_name: ezred2api
    image: ezred2api
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    ports:
      - 8000:8000
    restart: always

volumes:
  data: