"""empty message

Revision ID: 6f8f3cf3f58a
Revises: e44e12b99865
Create Date: 2025-08-22 15:04:00.388576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f8f3cf3f58a'
down_revision: Union[str, None] = 'e44e12b99865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('MULE_ACCEPT_BANK', name='character_action'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
