"""empty message

Revision ID: e44e12b99865
Revises: 8d5979018d28
Create Date: 2025-08-10 15:00:24.815091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44e12b99865'
down_revision: Union[str, None] = '8d5979018d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_price_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('item_price_history_gid_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_price_history', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('item_price_history_gid_key'), ['gid'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
