"""empty message

Revision ID: ade308edf9a6
Revises: 6f8f3cf3f58a
Create Date: 2026-01-03 15:18:32.674941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade308edf9a6'
down_revision: Union[str, None] = '6f8f3cf3f58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_price', sa.Integer(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_price_history', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('average_price')

    # ### end Alembic commands ###
